#!/bin/sh
set -e

chmod 6755 /usr/libexec/fontchange-helper
chown root:wheel /usr/libexec/fontchange-helper
if command -v uicache >/dev/null 2>&1; then
    uicache -p /Applications/FontChange.app || true
fi

exit 0
