#!/bin/sh
set -e

chmod 6755 /usr/libexec/fontchange-helper
chown root:wheel /usr/libexec/fontchange-helper
chmod 0644 /Library/LaunchDaemons/com.moxuan1121.fontchange.restore.plist
chown root:wheel /Library/LaunchDaemons/com.moxuan1121.fontchange.restore.plist

if command -v uicache >/dev/null 2>&1; then
    uicache -p /Applications/FontChange.app || true
fi

exit 0

