#!/bin/sh
set -e

chmod 6755 /var/jb/usr/libexec/fontchange-helper
chown root:wheel /var/jb/usr/libexec/fontchange-helper
chmod 6755 /var/jb/usr/libexec/fontchange-mount
chown root:wheel /var/jb/usr/libexec/fontchange-mount
chown root:wheel /var/jb/Library/LaunchDaemons/com.moxuan.fontchange.mount.plist
chmod 644 /var/jb/Library/LaunchDaemons/com.moxuan.fontchange.mount.plist
/var/jb/usr/libexec/fontchange-mount mount-if-enabled >/dev/null 2>&1 || true
if command -v uicache >/dev/null 2>&1; then
    uicache -p /var/jb/Applications/FontChange.app || true
fi

exit 0
